version: '3.9'

services:
  app-1:
    image: 'weather:latest'
    build:
      context: .
    ports:
        - "9595:8080"
    environment:
      - "WEATHER_STACK_API_KEY=${WEATHER_STACK_API_KEY}"
    networks:
      - weather-network
  app-2:
    image: 'weather:latest'
    build:
      context: .
    ports:
      - "9596:8080"
    environment:
      - "WEATHER_STACK_API_KEY=${WEATHER_STACK_API_KEY}"
    networks:
      - weather-network
networks:
    weather-network: